# Generated by Django 3.2.13 on 2023-04-26 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperlink', models.TextField(blank=True, max_length=500, null=True, unique=True)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('fullpost', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name_plural': 'AllContents',
                'ordering': ['hyperlink'],
            },
        ),
        migrations.CreateModel(
            name='AllPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchortext', models.TextField(blank=True, max_length=500, null=True)),
                ('hyperlink', models.TextField(blank=True, max_length=500, null=True)),
                ('user_search_terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('url', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'AllPosts',
                'ordering': ['anchortext'],
            },
        ),
        migrations.CreateModel(
            name='SearchTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchterm', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'SearchTerms',
            },
        ),
    ]
