# Generated by Django 3.2.13 on 2023-06-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20230622_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcontents',
            options={'ordering': ['url'], 'verbose_name_plural': 'AllContents'},
        ),
        migrations.RenameField(
            model_name='allcontents',
            old_name='hyperlink',
            new_name='url',
        ),
    ]
