# Generated by Django 3.2.13 on 2023-06-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_newallcontents_newallposts_newsearchterms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newallcontents',
            options={'ordering': ['hyperlink'], 'verbose_name_plural': 'NEWAllContents'},
        ),
        migrations.AlterModelOptions(
            name='newallposts',
            options={'ordering': ['title'], 'verbose_name_plural': 'NEWAllPosts'},
        ),
        migrations.AlterModelOptions(
            name='newsearchterms',
            options={'verbose_name_plural': 'NEWSearchTerms'},
        ),
    ]
