# Generated by Django 3.2.13 on 2023-06-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20230615_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='allposts',
            name='postid',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
