# Generated by Django 3.2.13 on 2023-06-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20230623_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allposts',
            options={'ordering': ['title'], 'verbose_name_plural': 'AllPosts'},
        ),
        migrations.RenameField(
            model_name='allposts',
            old_name='anchortext',
            new_name='title',
        ),
    ]
